language: python
sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
    - tree

install:
  - nvm install 5.5
  - nvm use 5.5
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install coveralls
  - npm install -g less
  - npm install -g less-plugin-autoprefix
  - npm install -g less-plugin-clean-css
  - npm install -g less-plugin-inline-urls
  - npm install -g babel-cli
  - npm install -g browserify
  - npm install -g uglify-js

# script: py.test -v --cov=dktasklib tests
script: py.test -v tests

#after_success:
#  coveralls
