language: python

sudo: false

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - npm install less
  - npm install less-plugin-autoprefix
  - npm install less-plugin-clean-css
  - npm install less-plugin-inline-urls

script: py.test -v --cov=dktasklib .

after_success:
  coveralls
