language: python

python:
  - "2.7"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tree

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - npm install less
  - npm install less-plugin-autoprefix
  - npm install less-plugin-clean-css
  - npm install less-plugin-inline-urls

script: py.test -v --cov=dktasklib tests

after_success:
  coveralls
